apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: wolfweb
    app.kubernetes.io/version: v0.0.1
  name: wolfweb
  namespace: wolf
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wolfweb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wolfweb
        app.kubernetes.io/version: v0.0.1
    spec:
      containers:
        - image: dockerhub.deepglint.com/deepface/wolfweb:0.0.1
          name: wolfweb
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 250m
              memory: 180Mi
            requests:
              cpu: 102m
              memory: 180Mi
          volumeMounts:
            - mountPath: /hostfs
              mountPropagation: HostToContainer
              name: root
              readOnly: true
          env:
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_PROC
              value: /hostfs/proc
            - name: HOST_SYS
              value: /hostfs/sys
            - name: HOST_ETC
              value: /hostfs/etc
            - name: HOST_VAR
              value: /hostfs/var
            - name: HOST_RUN
              value: /hostfs/run
          ports:
            - containerPort: 9998
              hostPort: 9998
              name: http
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      tolerations:
        - operator: Exists
      volumes:
        - hostPath:
            path: /
          name: root
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%